Datasets:
  dev:
    batch_size: 16
    class_name: att_speech.data.ConfigurableData
    dataset:
      class_name: egs.wsj.data.WSJDataset
      data_dir: exp/wsjs5/pydata/fbank80/test_dev93/
      feat_dim:
      - -1
      - 3
      - 81
      feat_dim_shuffle:
      - 0
      - 2
      - 1
      feat_input_file: feats.scp
      feat_pipeline: apply-cmvn exp/wsjs5/pydata/fbank80/train_si284/cmvn %s %s 2>/dev/null
      graph_generator: &id001
        class_name: CTCGraphGen
        context_order: 1
      vocab_file: egs/wsj/vocabulary.txt
    num_workers: 1
    pin_memory: false
  train:
    batch_size: 16
    class_name: att_speech.data.ConfigurableData
    dataset:
      class_name: egs.wsj.data.WSJDataset
      data_dir: exp/wsjs5/pydata/fbank80/train_si284/
      feat_dim:
      - -1
      - 3
      - 81
      feat_dim_shuffle:
      - 0
      - 2
      - 1
      feat_input_file: feats.scp
    : feat_pipeline: apply-cmvn exp/wsjs5/pydata/fbank80/train_si284/cmvn %s %s 2>/dev/null
      graph_generator: *id001
      vocab_file: egs/wsj/vocabulary.txt
    num_workers: 2
    pin_memory: false
    shuffle: true
Model:
  class_name: att_speech.models.SpeechModel
  decoder:
    class_name: att_speech.modules.decoders.advanced_decoder.FSTDecoder
    denominator_red: none
    graph_generator: *id001
    normalize_by_dim: 0
  encoder:
    class_name: att_speech.modules.encoders.DeepSpeech2
    conv_kernel_sizes:
    - - 7
      - 7
    - - 7
      - 7
    conv_strides:
    - - 1
      - 2
    - - 3
      - 1
    rnn_normalization: none
    rnn_hidden_size: 320
    rnn_nb_layers: 4
Trainer:
  checkpointer:
    every_n_hours: 1
  dump_logits_on_eval: true
  hooks:
    GradientClipping:
      clip_norm: 100.0
    LinearIncreaseWeightNoise:
      start_iteration: 20000
      weight_noise: 0.115
    PolyakDecay:
      decay_rates:
      - 0.9998
  learning_rate: 0.001
  learning_rate_scheduler:
    class_name: torch.optim.lr_scheduler.ReduceLROnPlateau
    factor: 0.5
    patience: 3
  num_epochs: 100
  optimizer_name: Adam
  print_num_decoding_samples: 1
